---
- hosts: all
  vars:
    nameservers: ["1.1.1.1"]
    ansible_folder: "/tmp/ansible"

  tasks:
    - name: load variables
      include_vars: "/tmp/config.json"

    - name: setup resolv.conf
      file:
        src: '/run/systemd/resolve/stub-resolv.conf'
        dest: '/etc/resolv.conf'
        force: yes
        owner: root
        group: root
        state: link

    - name: Install packages
      pacman:
        name:
          - sudo
          - vi
          - nginx
          - gd
        state: present

    - name: Install fswebcam
      copy:
        src: '{{files_folder}}/fswebcam'
        dest: '/usr/local/bin/fswebcam'
        owner: 'root'
        group: 'root'
        mode: '0755'

    - name: configure nginx
      systemd:
        name: nginx
        enabled: 'yes'

    - name: install fswebcam systemd unit
      copy:
        src: '{{files_folder}}/fswebcam.service'
        dest: '/etc/systemd/system/fswebcam.service'
        owner: 'root'
        group: 'root'
        mode: '0755'

    - name: enable fswebcam unit
      systemd:
        name: 'fswebcam'
        daemon_reload: 'yes'
        enabled: 'yes'
